// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using moveis_planejados.Models;

namespace moveis_planejados.Migrations
{
    [DbContext(typeof(MoveisPlanejadosContext))]
    partial class MoveisPlanejadosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("moveis_planejados.Models.Funcionario", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StatusFuncionario")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("FuncionarioId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("moveis_planejados.Models.Movel", b =>
                {
                    b.Property<int>("MovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Imagem")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Material")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Medidas")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("MovelId");

                    b.ToTable("Moveis");
                });

            modelBuilder.Entity("moveis_planejados.Models.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("MovelId")
                        .HasColumnType("int");

                    b.Property<string>("StatusVenda")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("Valor")
                        .HasColumnType("float");

                    b.HasKey("VendaId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("MovelId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("moveis_planejados.Models.Venda", b =>
                {
                    b.HasOne("moveis_planejados.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("moveis_planejados.Models.Movel", "Movel")
                        .WithMany()
                        .HasForeignKey("MovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
